### ISSUE TITLE
http3问题

### ISSUE THREAD

**Issue by heixiaoma** [silence934/http3#1]
老哥我用demo跑了下hosts已经配置，但是访问出现了404
Google浏览器不显示协议
![image](https://user-images.githubusercontent.com/10923974/202850194-d63a521a-c5a0-4971-a884-8b625f78a4ca.png)

火狐如下：
![image](https://user-images.githubusercontent.com/10923974/202850223-4f801915-d0a9-4a3c-9fc9-fb2287e167eb.png)

**Comment by heixiaoma** [comment]
两个浏览器都开启了http3配置
![image](https://user-images.githubusercontent.com/10923974/202850276-1f584f10-b970-471e-b357-bc6e2099aa03.png)
![image](https://user-images.githubusercontent.com/10923974/202850290-123fb681-15b9-4749-aa71-3af2094cddf5.png)

**Comment by silence934** [comment]
mac os使用/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --quic-version=h3-29 --origin-to-force-quic-on=http3.nyist.xyz:443 命令，强制该域名使用h3协议，否则不会自己开启的

**Comment by silence934** [comment]
> 两个浏览器都开启了http3配置 ![image](https://user-images.githubusercontent.com/10923974/202850276-1f584f10-b970-471e-b357-bc6e2099aa03.png) ![image](https://user-images.githubusercontent.com/10923974/202850290-123fb681-15b9-4749-aa71-3af2094cddf5.png)
mac os使用/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --quic-version=h3-29 --origin-to-force-quic-on=http3.nyist.xyz:443 命令，强制该域名使用h3协议，否则不会自己开启的

**Comment by heixiaoma** [comment]
> > 两个浏览器都开启了http3配置 ![image](https://user-images.githubusercontent.com/10923974/202850276-1f584f10-b970-471e-b357-bc6e2099aa03.png) ![image](https://user-images.githubusercontent.com/10923974/202850290-123fb681-15b9-4749-aa71-3af2094cddf5.png)
> > mac os使用/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --quic-version=h3-29 --origin-to-force-quic-on=http3.nyist.xyz:443 命令，强制该域名使用h3协议，否则不会自己开启的

![image](https://user-images.githubusercontent.com/10923974/202889318-e7b948a7-f90f-482c-8b01-734b4cffa793.png)
https://quic.nginx.org/test
这个网站是如何做到自动转换到http3的呢？只需要开启http3配置就可以了

**Comment by silence934** [comment]
> > > 两个浏览器都开启了http3配置 ![image](https://user-images.githubusercontent.com/10923974/202850276-1f584f10-b970-471e-b357-bc6e2099aa03.png) ![image](https://user-images.githubusercontent.com/10923974/202850290-123fb681-15b9-4749-aa71-3af2094cddf5.png)
> > > mac os使用/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --quic-version=h3-29 --origin-to-force-quic-on=http3.nyist.xyz:443 命令，强制该域名使用h3协议，否则不会自己开启的
> 
> ![image](https://user-images.githubusercontent.com/10923974/202889318-e7b948a7-f90f-482c-8b01-734b4cffa793.png) https://quic.nginx.org/test 这个网站是如何做到自动转换到http3的呢？只需要开启http3配置就可以了

文档要求在header中添加 alt-svc: h3=":443"; ma=86400  可以进行协议升级，我在curl中测试成功，但是在chrome中实验是无法生效的，只能强制使用h3，这个问题暂时没有找到答案

**Comment by heixiaoma** [comment]
> > > > 两个浏览器都开启了http3配置 ![image](https://user-images.githubusercontent.com/10923974/202850276-1f584f10-b970-471e-b357-bc6e2099aa03.png) ![image](https://user-images.githubusercontent.com/10923974/202850290-123fb681-15b9-4749-aa71-3af2094cddf5.png)
> > > > mac os使用/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --quic-version=h3-29 --origin-to-force-quic-on=http3.nyist.xyz:443 命令，强制该域名使用h3协议，否则不会自己开启的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/10923974/202889318-e7b948a7-f90f-482c-8b01-734b4cffa793.png) https://quic.nginx.org/test 这个网站是如何做到自动转换到http3的呢？只需要开启http3配置就可以了
> 
> 文档要求在header中添加 alt-svc: h3=":443"; ma=86400 可以进行协议升级，我在curl中测试成功，但是在chrome中实验是无法生效的，只能强制使用h3，这个问题暂时没有找到答案

我用mac体验下看看
